version: '2'

services:
  web1:
    image: nginx
    hostname: web1
    volumes:
      - ./nginx_conf:/etc/nginx/templates
    environment:
      - NGINX_PORT=5000

  web2:
    image: nginx
    hostname: web2
    volumes:
      - ./nginx_conf:/etc/nginx/templates
    environment:
      - NGINX_PORT=5000

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: always
    hostname: hapro
    volumes:
      - ./haproxy_conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
